[project]
site_name = "Python Build123d para Arquitetos e Engenheiros"
site_url = "https://255ribeiro.github.io/python_build123d_basics/"
copyright = "Copyright &copy; 2026 Fernando Ferraz Ribeiro"
repo_url = "https://github.com/255ribeiro/python_build123d_basics/"
repo_name = "255ribeiro/python_build123d_basics"
use_directory_urls = false
extra_css = ["overrides/css/extra_css.css"]

# Legacy MkDocs nav entries that do not exist anymore:
# - ./tuto_colab_build/cadquery_basic_gc.ipynb
# - ./tuto_colab_build/cadquery_primitives_gc.ipynb
# - ./tuto_colab_build/cadquery_trusses_gc.ipynb
# - ./tuto_colab_build/cadquery_multiplos_pav.ipynb
# - ./tuto_colab_build/multi_pav_cq_resolvido.ipynb
# - ./tuto_colab_build/cadquery_multiplos_pav_perfil.ipynb
# - ./tuto_colab_build/multi_pav_cq_ramdom_disp_resolvido.ipynb

nav = [
  { Home = "index.md" },
  { "Google Colab: intro" = "./tuto_colab_build/build123d_basic_gc.ipynb" },
  { "Google Colab: primitivas" = "./tuto_colab_build/build123d_primitives_gc.ipynb" },
  { "Google Colab: treliças" = "./tuto_colab_build/build123d_trusses_gc.ipynb" },
  { "Google Colab: Modelagem" = "./tuto_colab_build/2d_to_3d.ipynb" },
  { "Google Colab: Exercício multi pav" = "./tuto_colab_build/build123d_multiplos_pav.ipynb" },
  { "Google Colab: Exercício multi pav resolvido" = "./tuto_colab_build/multi_pav_b3d_resolvido.ipynb" },
  { "Google Colab: Exercício multi pav perfil" = "./tuto_colab_build/build123d_multiplos_pav_perfil.ipynb" },
  { "Google Colab: Exercício pavimentos deslocados" = "./tuto_colab_build/multi_pav_b3d_ramdom_disp_resolvido.ipynb" },
  { "Google Colab: Criando volumes com o loft" = "./tuto_colab_build/multi_pav_loft.ipynb" },
  { "Google Colab: Exportação IFC" = "./tuto_colab_build/step_to_ifc.ipynb" },
  { "Google Colab: Exportação IFC Mesh" = "./tuto_colab_build/step_to_ifc_mesh.ipynb" },
  { "Apêndice: Matrizes de transformação" = "./conceitos/matrizes_de_transformacao.md" },
  { "Apêndice: Geometria Descritiva vs. Projetiva" = "./conceitos/descritiva_vs_projetiva.md" },
  { "Apêndice: Github Copiplot para professores e estudantes" = "./conceitos/Resumo_GitHub_Copilot_Educacao_2026.md" },
  { Downloads = "./down_files/down_files.md" },
]

[project.theme]
variant = "classic"
language = "en-custom"
custom_dir = "docs/overrides"
features = ["toc.integrate"]

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "material/toggle-switch-off-outline"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "orange"
accent = "deep orange"
toggle.icon = "material/toggle-switch"
toggle.name = "Switch to light mode"

[project.markdown_extensions]
admonition = {}
pymdownx.details = {}
pymdownx.superfences = {}
attr_list = {}
toc = { toc_depth = 1 }

[project.plugins]
mkdocs-jupyter = { execute = false, include_source = true }
